# Generated by Django 2.1.1 on 2018-09-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0010_auto_20180927_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(default=1, on_delete=True, to='ecomapp.Cart'),
            preserve_default=False,
        ),
    ]
